include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore
    unused_element: ignore
    unused_field: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    avoid_print: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    use_key_in_widget_constructors: false
